stages:
  train_lstm_baseline:
    cmd: python scripts/train_captioning.py --model lstm
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/lstm.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - data
     - tokenizer
     - train
     - preprocess
     - captioning


  train_gru_baseline:
    cmd: python scripts/train_captioning.py --model gru
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/gru.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - data
     - tokenizer
     - train
     - preprocess
     - captioning


  train_transformer_baseline:
    cmd: python scripts/train_captioning.py --model transformer
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/transformer.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - data
     - tokenizer
     - train
     - preprocess
     - captioning


  train_resnet18_baseline:
    cmd: python scripts/train_classification.py --model resnet18 --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/resnet18.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_efficientnet_b0_baseline:
    cmd: python scripts/train_classification.py --model efficientnet_b0 --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/efficientnet.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_convnext_tiny_baseline:
    cmd: python scripts/train_classification.py --model convnext_tiny --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/convnext.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_mobilenet_v3_small_baseline:
    cmd: python scripts/train_classification.py --model mobilenet_v3_small --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/mobilenet.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_vit_b_16_baseline:
    cmd: python scripts/train_classification.py --model vit_b_16 --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/vit.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_swin_t_baseline:
    cmd: python scripts/train_classification.py --model swin_t --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/swin.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_deit_tiny_patch16_224_baseline:
    cmd: python scripts/train_classification.py --model deit_tiny_patch16_224 --augmentation none
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/deit.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_best_backbone_mixup:
    cmd: python scripts/train_classification.py --model convnext_tiny --augmentation mixup
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/convnext.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  train_best_backbone_cutmix:
    cmd: python scripts/train_classification.py --model convnext_tiny --augmentation cutmix
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/models/convnext.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
    params:
     - data.dataset_version
     - train
     - preprocess
     - classification




