stages:
  train_lstm_baseline:
    cmd: python scripts/train_captioning.py --model lstm
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/lstm.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - train
     - preprocess
     - captioning


  train_gru_baseline:
    cmd: python scripts/train_captioning.py --model gru
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/gru.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - train
     - preprocess
     - captioning


  train_transformer_baseline:
    cmd: python scripts/train_captioning.py --model transformer
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/models/resnet18.py
     - src/models/transformer_.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - train
     - preprocess
     - captioning


  train_transformer_scratch_baseline:
    cmd: python scripts/train_captioning.py --model transformer_scratch
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/metrics/make_show_all_caption.py
     - src/models/resnet18.py
     - src/models/vit.py
     - src/models/swin.py
     - src/models/transformer_scratch.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - train
     - preprocess
     - captioning


  train_classification:
    cmd: python scripts/train_classification.py
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
     - src/models/resnet18.py
     - src/models/efficientnet.py
     - src/models/convnext.py
     - src/models/mobilenet.py
     - src/models/vit.py
     - src/models/swin.py
     - src/models/deit.py

    params:
     - data.dataset_version
     - train
     - preprocess
     - classification




