stages:
  train_captioning:
    cmd: python scripts/train_captioning.py
    deps:
     - data/captioning/annotations/train.json
     - data/captioning/annotations/val.json
     - data/captioning/annotations/test.json
     - src/dataset/captioning_dataset.py
     - src/dataset/build_vocab.py
     - src/dataset/collate_caption.py
     - src/dataset/train_sub_tokenizer.py
     - src/dataset/sub_tokenizer1000.vocab
     - src/dataset/sub_tokenizer1000.model
     - src/dataset/sub_tokenizer1500.vocab
     - src/dataset/sub_tokenizer1500.model
     - src/dataset/sub_tokenizer2000.vocab
     - src/dataset/sub_tokenizer2000.model
     - src/engines/captioning_trainer.py
     - src/engines/captioning_validator.py
     - src/metrics/evaluate_caption.py
     - src/metrics/make_show_all_caption.py
     - src/models/resnet18.py
     - src/models/vit.py
     - src/models/swin.py
     - src/models/transformer.py
     - src/models/lstm.py
     - src/models/gru.py
     - src/transforms/image_transform.py
     - scripts/train_captioning.py
    params:
     - train
     - preprocess
     - captioning


  train_classification:
    cmd: python scripts/train_classification.py
    deps:
     - scripts/train_classification.py
     - src/dataset/classification_dataset.py
     - src/engines/classification_trainer.py
     - src/engines/classification_validator.py
     - src/transforms/image_transform.py
     - src/transforms/mixup.py
     - src/transforms/cutmix.py
     - src/models/resnet18.py
     - src/models/efficientnet.py
     - src/models/convnext.py
     - src/models/mobilenet.py
     - src/models/vit.py
     - src/models/swin.py
     - src/models/deit.py

    params:
     - data.dataset_version
     - train
     - preprocess
     - classification


  evaluate_classification:
    cmd: python scripts/evaluate_classification.py

    deps:
     - scripts/evaluate_classification.py
     - src/dataset/classification_dataset.py
     - src/transforms/image_transform.py
     - src/models/swin.py
     - src/visualization/generate_gradcam.py

    params:
     - data.dataset_version
     - classification.final_checkpoint

    outs:
     - outputs/classification/metrics.json
     - outputs/classification/predictions.csv
     - outputs/classification/classification_report.txt
     - outputs/classification/confusion_matrix.png
     - outputs/classification/correct_examples
     - outputs/classification/incorrect_examples


